src/models/contacts.py
from utils.db import db
class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100), nullable=False, unique=True)
    phone = db.Column(db.String(100), nullable=False, unique=True)

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

src/app.py
import os
import sentry_sdk
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION 
from flask import Flask
from sentry_sdk.integrations.flask import FlaskIntegration

sentry_sdk.init(
    dsn="https://0638fb48cd26422c8af88c268b0a8b85@o1275124.ingest.sentry.io/6523802",
    integrations=[
        FlaskIntegration(),
    ],
    traces_sample_rate=1.0
)

app = Flask(__name__)

app.secret_key = "Asterisk.123"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION 
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_MAX_OVERFLOW'] = -1

SQLAlchemy(app)

app.register_blueprint(contacts)

src/routes/contacts.py
from crypt import methods
from flask import Blueprint, redirect, render_template, request, flash
from models.contacts import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)


@contacts.route('/')
def index():
    contacts = Contact.query.all()
    db.session.commit()

    return render_template('index.html', contacts=contacts)
    


@contacts.route('/new', methods=['POST'])
def add_contact():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()


    flash("Contacto fue agregado!")

    return redirect('/')


@contacts.route('/update/<id>', methods=['POST', 'GET'])
def update(id):
    contact = Contact.query.get(id)
    if request.method == 'POST':
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]
        db.session.commit()

        flash("Contacto fue actualizado!")

        return redirect('/')

    return render_template("update.html", contact=contact)


@contacts.route('/delete/<id>')
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)

    flash("Contacto fue eliminado!")

    return redirect('/')


@contacts.route("/about")
def about():
    db.session.commit()
    return render_template('about.html')

src/templates/about.html
{% extends 'layout.html' %}
    
    {% block content %}

<h3 class="text-white">Este proyecto fue realizado con propositos de pruebas, podra encontrar este proyecto en github account: hola julio</h3>

{% endblock %}

src/templates/index.html
{% extends 'layout.html' %}

{% block content %}

<div class="row">

    <div class="col-md-5">
        {% include 'partials/message.html' %}

        {% include 'partials/contactform.html' %}
    </div>

    <div class="col-md-7">
        {% for contact in contacts %}

        <div class="card mb-1 text-white bg-dark">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                     <h5>{{contact.fullname}}</h5>
                     <div>
                          <a href="{{ url_for('contacts.update', id=contact.id)}}"
                          class="btn btn-dark btn-sm rounded-0">Update</a>
                          <a href="{{ url_for('contacts.delete', id=contact.id)}}"
                          class="btn btn-danger btn-sm rounded-0">Delete</a>
                     </div>
                </div>
           
                <p>{{contact.phone}}</p>
                <p>{{contact.email}}</p>

            </div>


        </div>
        {% endfor %}



    </div>

    {% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Flask CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"  
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">

</head>

<body>
    
    {% include('partials/navbar.html') %}


    <div class="container p-2">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

src/templates/partials/contactform.html
<form action="/new" method="POST" class="card bg-dark text-light">

    <div class="card-body p-4">

        <div class="mb-3">
            <label for="fullname">Escribe tu nombre:</label>
            <input type="text" name="fullname" placeholder="Escribe tu nombre"
                class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="email">Escribe tu email:</label>
            <input type="text" name="email" placeholder="Escribe tu email"
                class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>

        <div class="mb-3">
            <label for="phone">Escribe tu telefono:</label>
            <input type="text" name="phone" placeholder="Escribe tu telefono"
                class="form-control rounded-0 bg-dark border-0 text-white" />
        </div>


        <button class="btn btn-primary">Save</button>
    </div>
</form>

src/templates/partials/message.html
{% with messages = get_flashed_messages() %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{message}}
            </div>
          
            
        {% endfor %}
    {% endif %}

{% endwith %}

src/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">FLASK CRUD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="/about">about</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

src/templates/update.html
{% extends 'layout.html' %}
    
    {% block content %}

<form action="/update/{{contact.id}}" method="POST">

    <input type="text" name="fullname" placeholder="Escribe tu nombre" value="{{contact.fullname}}">
    <input type="text" name="email" placeholder="Escribe tu email" value="{{contact.email}}">
    <input type="text" name="phone" placeholder="Escribe tu telefono" value="{{contact.phone}}">

    <button>Save</button>

</form>

{% endblock %}